### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by wmvanvliet**
These changes make the pipeline work on Python 3 (and should not break compatibility with Python 2).

### CODE REVIEW

**Comment by ualsbombe** [comment]
Thanks a lot - will try to implement in the new year - on vacation now.

**Comment by ualsbombe** [comment]
Thanks, Marijn. I discovered one thing that breaks compatibility with python 2.7. From my tests, at least, it was not possible to do:
`from analysis_functions_frontiers import io_functions as io`
Can you change those parts and also change back to my paths instead of your local ones? And set all operations back to zero?
Finally, why do you import the print_function from  __future__. Is it because you want to force new contributions to use _print_ as a function, (which is fine by me, just checking?)

**Comment by wmvanvliet** [comment]
> Finally, why do you import the print_function from future. Is it because you want to force new contributions to use print as a function, (which is fine by me, just checking?)

Python3 can only use `print` as a function and syntax errors on using it as a keyword. By importing it from the future for Python2, the print function works the same across both versions.

**Comment by wmvanvliet** [comment]
I've tested this with Python2.7, all seems well now.

**Comment by ualsbombe** [comment]
Thanks for your changes. I think you forgot the `from analysis_functions_frontiers import io_functions as io` though. At least my python 2.7 environment throws an error here:

from analysis_functions_frontiers import io_functions as io
Traceback (most recent call last):

  File "<ipython-input-19-0e748bdffa99>", line 1, in <module>
    from analysis_functions_frontiers import io_functions as io

ImportError: No module named analysis_functions_frontiers

whereas it works fine in python 3.6

Any dependencies that one needs for python 2.7 to see local directories with the from statement?

**Comment by wmvanvliet** [comment]
How strange. This works on my end and should just work. As long as a directory has an `__init__.py` (even an empty one), it should register as a python package as long as it is in your current working directory.

If I remove `from analysis_functions_frontiers import io_functions as io`, Python3 will break (it doesn't like your `ch_dir` solution)

**Comment by ualsbombe** [comment]
Ok, there was no __init__.py in analysis_functions_frontiers. Adding that now made the "from"-type of importing possible also in python 2.7

**Comment by wmvanvliet** [comment]
Ah! I get it now. Since `__init__.py` was just an empty file, and git tracks content, not files, it was never added to the repository.

**Comment by ualsbombe** [comment]
Ok, makes sense - now it is there, and as a side effect I learnt what __init__.py is good for

**Pull request merged**
